apiVersion: v1
kind: Service
metadata:
  name: mp-client
  namespace: oteam-mvne-ns
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 18080
    protocol: TCP
  selector:
    app: mp-client
